#!/bin/bash

set -e

export FILENAME="$1"
java \
    -Dfile.encoding=UTF-8 \
    -classpath /Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/charsets.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/cldrdata.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/dnsns.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/jaccess.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/jfxrt.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/localedata.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/nashorn.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/sunec.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/ext/zipfs.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/jce.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/jfr.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/jfxswt.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/jsse.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/management-agent.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/resources.jar:/Users/eddie/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/jre/lib/rt.jar:/Users/eddie/repos/jungle/target/classes:/Users/eddie/.m2/repository/org/jetbrains/annotations/23.1.0/annotations-23.1.0.jar:/Users/eddie/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/eddie/.m2/repository/org/ow2/asm/asm/9.4/asm-9.4.jar \
        com.jungle.Jungle "$FILENAME" > /dev/null

java Entrypoint